version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
platform: Any CPU
cache:
- '%USERPROFILE%\.nuget\packages'
- '%LocalAppData%\NuGet\Cache'
- '%LocalAppData%\NuGet\v3-cache'
build_script:
- ps: "cd src\\Defaults \ndotnet pack -p:PackageVersion=$env:APPVEYOR_BUILD_VERSION \ncd ..\\..\\"
- ps: "cd src\\Multitargeting \ndotnet pack -p:PackageVersion=$env:APPVEYOR_BUILD_VERSION \ncd ..\\..\\"
artifacts:
- path: dist/*.nupkg
  name: NuGet Package
deploy:
- provider: NuGet
  api_key:
    secure: 9tjKpcQ5ppjbneqBIpe4WbyA8RxTtTk/NXjip+RlGvYqepAak1TvmaHtrspbeDon
  on:
    branch: master